Repository ttoklip/Android, pull requests merged in 2024-01, with the labels that each got.

#8 Feat/#7 Api 기초작업
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/ttoklip/TtoklipApplication.kt
  app/src/main/java/com/umc/ttoklip/data/api/TestApi.kt
  app/src/main/java/com/umc/ttoklip/data/model/TestResponse.kt
  app/src/main/java/com/umc/ttoklip/data/repository/TestRepository.kt
  app/src/main/java/com/umc/ttoklip/data/repository/TestRepositoryImpl.kt
  app/src/main/java/com/umc/ttoklip/di/NetworkModule.kt
  app/src/main/java/com/umc/ttoklip/module/AppConfig.kt
  app/src/main/java/com/umc/ttoklip/module/HandleApi.kt
  app/src/main/java/com/umc/ttoklip/module/HttpRequestInterceptor.kt
  app/src/main/java/com/umc/ttoklip/module/NetworkConnectionChecker.kt
  app/src/main/java/com/umc/ttoklip/module/NetworkResult.kt
  app/src/main/res/values/strings.xml
Labels: feat, 설계

#14 Fix: BaseActivity의 오류 수정
  app/src/main/java/com/umc/ttoklip/presentation/base/BaseActivity.kt
Labels: fix

#21 Faet/#2 마이페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/ttoklip/presentation/mypage/ChooseMainInterestDialogFragment.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/CustomerServiceCenterActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/ManageAccountActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/MyHoneyTipActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/NoticeSettingActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/SavedHoneyTipActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/SortSpinnerAdapter.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/TermsPolicesActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/TransactionHistoryActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/adapter/BlockUser.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/adapter/HoneyTips.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/adapter/SavedHoneyTipAdapter.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/adapter/Transaction.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/adapter/TransactionAdapter.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/dialog/LogoutDialog.kt
  app/src/main/java/com/umc/ttoklip/presentation/mypage/dialog/OneOnOneInquiriesDialog.kt
  app/src/main/res/drawable/ic_eye_on_black_24.xml
  app/src/main/res/drawable/rectangle_corner_right_10_stroke_1.xml
  app/src/main/res/drawable/sort_spinner_dropdown.xml
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/drawable/switch_track.xml
  app/src/main/res/layout/activity_customer_service_center.xml
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/activity_manage_usage.xml
  app/src/main/res/layout/activity_my_homtown_address.xml
  app/src/main/res/layout/activity_my_honey_tip.xml
  app/src/main/res/layout/activity_notice_setting.xml
  app/src/main/res/layout/activity_saved_honey_tip.xml
  app/src/main/res/layout/activity_terms_polices.xml
  app/src/main/res/layout/activity_transaction_history.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_one_on_one_inquries.xml
  app/src/main/res/layout/fragment_choose_main_interest.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_saved_honey_tip.xml
  app/src/main/res/layout/item_transaction_history.xml
  app/src/main/res/layout/spinner_sort_inner.xml
  app/src/main/res/layout/spinner_sort_outer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: feat

#22 Feat/#1 home news fragment
  app/build.gradle
  app/src/main/java/com/umc/ttoklip/di/NetworkModule.kt
  app/src/main/java/com/umc/ttoklip/presentation/news/ItemNewsFragment.kt
  app/src/main/java/com/umc/ttoklip/presentation/news/NewsFragment.kt
  app/src/main/java/com/umc/ttoklip/presentation/news/detail/ArticleActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/search/SearchActivity.kt
  app/src/main/java/com/umc/ttoklip/presentation/search/SearchViewModel.kt
  app/src/main/java/com/umc/ttoklip/presentation/search/SearchViewModelImpl.kt
  app/src/main/java/com/umc/ttoklip/presentation/search/adapter/HistoryModel.kt
  app/src/main/java/com/umc/ttoklip/presentation/search/adapter/HistoryRVA.kt
  app/src/main/java/com/umc/ttoklip/presentation/search/dialog/BottomDialogSearchFragment.kt
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_bottom_dialog_search.xml
  app/src/main/res/layout/fragment_item_news.xml
  app/src/main/res/layout/fragment_news.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_serach_history.xml
  app/src/main/res/values/strings.xml
Labels: feat

#27 Feat/#1 home news fragment
  app/src/main/java/com/umc/ttoklip/presentation/news/adapter/Comment.kt
  app/src/main/java/com/umc/ttoklip/presentation/news/adapter/CommentRVA.kt
  app/src/main/java/com/umc/ttoklip/presentation/news/detail/ArticleActivity.kt
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_home_honey_tip.xml
  app/src/main/res/layout/item_reply.xml
Labels: feat
